services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8088:8088"
    depends_on:
      pgsqldb:
        condition: service_healthy


  pgsqldb:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
